imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
        types:
          MessageServiceGatewayType: CoreDomain\MessageService\MessageServiceGatewayType
          MessageServiceType: CoreDomain\MessageService\MessageServiceType
          MessageDirectionType: CoreDomain\Contact\Message\MessageDirectionType
          MessageSenderAppType: CoreDomain\Contact\Message\MessageSenderAppType
          MessageGatewayStatusType: CoreDomain\Contact\Message\MessageGatewayStatusType
          ContactPresenceType: CoreDomain\Contact\ContactPresenceType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        entity_managers:
            default:
                mappings:
                    Company:
                        type: annotation
                        prefix: CoreDomain\Company\
                        dir: "%kernel.root_dir%/../src/CoreDomain/Company/"
                        is_bundle: false
                    Contact:
                        type: annotation
                        prefix: CoreDomain\Contact\
                        dir: "%kernel.root_dir%/../src/CoreDomain/Contact/"
                        is_bundle: false
                    Message:
                        type: annotation
                        prefix: CoreDomain\Contact\Message\
                        dir: "%kernel.root_dir%/../src/CoreDomain/Contact/Message/"
                        is_bundle: false
                    ContactExternalAccount:
                        type: annotation
                        prefix: CoreDomain\Contact\ContactExternalAccount\
                        dir: "%kernel.root_dir%/../src/CoreDomain/Contact/ContactExternalAccount/"
                        is_bundle: false
                    MessageService:
                        type: annotation
                        prefix: CoreDomain\MessageService\
                        dir: "%kernel.root_dir%/../src/CoreDomain/MessageService/"
                        is_bundle: false
                    User:
                        type: annotation
                        prefix: CoreDomain\User\
                        dir: "%kernel.root_dir%/../src/CoreDomain/User/"
                        is_bundle: false


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
