version: "2"
services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./logs/nginx-proxy:/var/log/nginx
  nginx:
    image: nginx:latest
    #dockerfile: ./Dockerfile # путь до докер файла указываем относительно директории в build
    #build: ./contaners/nginx
    depends_on:
      - fpm
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./contaners/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - fpm:rw
    command: nginx -g "daemon off;" # Можно было указать в докер-фале, но можно и здесь)
    links:
      - fpm
  nodejs:
    build:
      context: ./contaners/nodejs
      dockerfile: ./Dockerfile
    volumes:
      - ./frontEnd:/var/www/ddd-sample:rw
      - ./logs/nodejs:/root/.npm/_logs
      - ./contaners/nodejs/init.sh:/root/init.sh:ro
    expose:
      - "80"
  fpm:
    build:
      context: ./contaners/fpm
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backEnd:/var/www/html:rw
      - ./contaners/fpm/init.sh:/root/init.sh:ro
    ports:
      - 8000:8000
    expose:
      - "9000"
    links:
      - postgres
  postgres:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./database/postgres:/data/postgres
    environment:
      POSTGRES_PASSWORD: kjshdfks_32sd
      POSTGRES_USER: postgres
      POSTGRES_DB: ddd-sample
      PGDATA : /data/postgres