<?php
namespace InfrastructureLayerBundle\Repository;

use DomainLayer\Contact\Contact;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use DomainLayer\Contact\ContactExternalAccount\ContactExternalAccount;
use DomainLayer\Contact\ContactExternalAccount\ContactExternalAccountRepositoryInterface;
use DomainLayer\Contact\ContactRepositoryInterface;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostgresContactRepository extends \Doctrine\ORM\EntityRepository implements ContactRepositoryInterface
{
    /** @var ContactExternalAccountRepositoryInterface */
    private $externalAccountRepository;

    public function __construct(EntityManager $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->externalAccountRepository = $this->_em->getRepository(ContactExternalAccount::class);
    }

    public function prepareBatchSave(Contact $contact)
    {
        $this->_em->persist($contact);
    }

    public function doBatchSave()
    {
        $this->_em->flush();
    }

    public function save(Contact $contact)
    {
        $this->_em->persist($contact);
        $this->_em->flush($contact);
    }
}
