<?php
namespace InfrastructureLayerBundle\Repository;

use DomainLayer\Company\Company;
use DomainLayer\Company\CompanyRepositoryInterface;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostgresCompanyRepository extends \Doctrine\ORM\EntityRepository implements CompanyRepositoryInterface
{
    public function prepareBatchSave(Company $company)
    {
        $this->_em->persist($company);
    }

    public function doBatchSave()
    {
        $this->_em->flush();
    }

    public function save(Company $company)
    {
        $this->_em->persist($company);
        $this->_em->flush($company);
    }
}
