<?php
namespace InfrastructureLayerBundle\Repository;

use DomainLayer\MessageService\MessageService;
use DomainLayer\MessageService\MessageServiceRepositoryInterface;

/**
 * PostgresMessageServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostgresMessageServiceRepository extends \Doctrine\ORM\EntityRepository implements MessageServiceRepositoryInterface
{
    public function prepareBatchSave(MessageService $messageService)
    {
        $this->_em->persist($messageService);
    }

    public function doBatchSave()
    {
        $this->_em->flush();
    }

    public function save(MessageService $messageService)
    {
        $this->_em->persist($messageService);
        $this->_em->flush();
    }
}
