<?php
namespace InfrastructureLayerBundle\Repository;

use DomainLayer\Contact\ContactExternalAccount\ContactExternalAccount;
use DomainLayer\Contact\ContactExternalAccount\ContactExternalAccountRepositoryInterface;

/**
 * ContactExternalAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostgresContactExternalAccountRepository extends \Doctrine\ORM\EntityRepository implements ContactExternalAccountRepositoryInterface
{
    public function prepareBatchSave(ContactExternalAccount $contactExternalAccount)
    {
        $this->_em->persist($contactExternalAccount);
    }

    public function doBatchSave()
    {
        $this->_em->flush();
    }

    public function save(ContactExternalAccount $contactExternalAccount)
    {
        $this->_em->persist($contactExternalAccount);
        $this->_em->flush($contactExternalAccount);
    }
}
