services:
    infrastructure.repository.contact:
        class: DomainLayer\Contact\ContactRepositoryInterface
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Contact\Contact
    infrastructure.repository.contact_external_account:
        class: DomainLayer\Contact\ContactExternalAccount\ContactExternalAccountRepositoryInterface
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Contact\ContactExternalAccount\ContactExternalAccount
    infrastructure.repository.user:
        class: DomainLayer\User\UserRepositoryInterface
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\User\User
    infrastructure.repository.company:
        class: DomainLayer\Company\CompanyRepositoryInterface
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Company\Company
    infrastructure.repository.message:
        class: DomainLayer\Contact\Message\MessageRepositoryInterface
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Contact\Message\Message
    infrastructure.repository.message_service:
        class: DomainLayer\MessageService\MessageServiceRepositoryInterface
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\MessageService\MessageService

    http_client:
        class: GuzzleHttp\Client