services:
    infrastructure.repository.contact:
        class: InfrastructureLayerBundle\Repository\PostgresContactRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Contact\Contact
    infrastructure.repository.contact_external_account:
        class: InfrastructureLayerBundle\Repository\PostgresContactExternalAccountRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Contact\ContactExternalAccount\ContactExternalAccount
    infrastructure.repository.user:
        class: InfrastructureLayerBundle\Repository\PostgresUserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\User\User
    infrastructure.repository.company:
        class: InfrastructureLayerBundle\Repository\PostgresCompanyRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Company\Company
    infrastructure.repository.message:
        class: InfrastructureLayerBundle\Repository\PostgresMessageRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\Contact\Message\Message
    infrastructure.repository.message_service:
        class: InfrastructureLayerBundle\Repository\PostgresMessageServiceRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DomainLayer\MessageService\MessageService

    http_client:
        class: GuzzleHttp\Client